-- COPIA Y PEGA ESTO EN EL EDITOR SQL DE SUPABASE
-- Tablas adicionales para el inventario de Brada Perfumes

-- 1. Brada Perfumes (Stock)
create table if not exists public.brada_perfumes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  perfume text,
  stock numeric default 0,
  precio numeric default 0,
  disponibilidad boolean default true
);

-- 2. Brada Decants
create table if not exists public.brada_decants (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text,
  decants text, -- e.g. "5ml, 10ml" or specific types
  precio_5ml numeric default 0,
  precio_10ml numeric default 0,
  disponibilidad boolean default true
);

-- 3. Brada Sets
create table if not exists public.brada_perfume_sets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  set_de_perfumes text,
  stock numeric default 0,
  precio numeric default 0,
  disponibilidad boolean default true
);

-- Habilitar RLS
alter table public.brada_perfumes enable row level security;
alter table public.brada_decants enable row level security;
alter table public.brada_perfume_sets enable row level security;

-- Políticas de acceso (Permitir todo temporalmente)
create policy "Enable all access for Brada Perfumes" on public.brada_perfumes for all using (true);
create policy "Enable all access for Brada Decants" on public.brada_decants for all using (true);
create policy "Enable all access for Brada Sets" on public.brada_perfume_sets for all using (true);
