-- COPIA Y PEGA ESTO EN EL EDITOR SQL DE SUPABASE PARA EL NUEVO PANEL "SOLARI"

/* =========================================
   1. TABLAS PRINCIPALES (SOLARI)
   ========================================= */

-- 1.1 Procedimientos Solari
create table if not exists public.solari_procedures (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  color text,
  price numeric default 0,
  discount numeric default 0
);

-- 1.2 Eventos Calendario Solari
create table if not exists public.solari_calendar_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date text not null,
  time text not null,
  subject text not null,
  description text,
  procedure_id bigint, 
  client_name text,
  client_surname text,
  client_dni text,
  event_reason text
);

-- 1.3 Historial Médico Solari
create table if not exists public.solari_medical_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  surname text not null,
  dni text not null,
  phone text,
  email text,
  date_added text,
  attachment_name text,
  attachment_data text
);

-- 1.4 Sistema de Egresos Solari
create table if not exists public.egresos_solari (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tipo_egreso text not null,
  nombre text not null,
  precio numeric default 0,
  cantidad integer default 1,
  company_id text
);

-- 1.5 Horarios de Calendario (Working Hours)
create table if not exists public.solari_working_hours (
  id integer primary key, -- 0 a 6 referenciando los días de la semana
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  day_of_week text,
  is_working_day boolean default true,
  start_time text default '08:00',
  end_time text default '18:00',
  slot_duration_minutes integer default 30
);

/* =========================================
   2. TABLAS INTEGRADAS O DE LEADS/VENTAS
   ========================================= */
-- Es muy probable que estas tablas vengan desde N8N, aquí te dejo la estructura básica recomendada.

create table if not exists public."PacientesBDwppSOLARI" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text,
  telefono text,
  lead_status text
);

create table if not exists public."PacientesBDfbigSOLARI" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text,
  telefono text,
  lead_status text
);

create table if not exists public."GeneralBDwppSOLARI" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text,
  telefono text,
  lead_status text
);

create table if not exists public."GeneralBDfbigSOLARI" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text,
  telefono text,
  lead_status text
);

-- Tabla de Compras
create table if not exists public."comprasBDwppSOLARI" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text,
  apellidos text,
  telefono text,
  productos_comprados text,
  precio numeric
);

/* =========================================
   3. POLÍTICAS DE SEGURIDAD (RLS) GLOBALES
   ========================================= */

-- Activando RLS (Row Level Security) básico para evitar bloqueos
alter table public.solari_procedures enable row level security;
alter table public.solari_calendar_events enable row level security;
alter table public.solari_medical_history enable row level security;
alter table public.egresos_solari enable row level security;
alter table public.solari_working_hours enable row level security;

-- Creando políticas permisivas, luego puedes ajustarlas a roles específicos
create policy "Enable all access for Solari Procedures" on public.solari_procedures for all using (true);
create policy "Enable all access for Solari Events" on public.solari_calendar_events for all using (true);
create policy "Enable all access for Solari Medical" on public.solari_medical_history for all using (true);
create policy "Enable all access for Solari Egresos" on public.egresos_solari for all using (true);
create policy "Enable all access for Solari Working Hours" on public.solari_working_hours for all using (true);
