-- ══════════════════════════════════════════════════════════════════════════
-- DAVILA — SQL COMPLETO: pre-reservas + calendario del dashboard
--
-- Pegá TODO esto en Supabase → SQL Editor y dale Run. Es idempotente y seguro:
-- no borra filas; solo crea/ajusta lo que falte.
--
-- Cubre:
--   1. Tabla pre_reservas (estructura final, 4-parámetros) — por si no existe
--   2. Columna dashboard_event_id en pre_reservas (link al calendario del dashboard)
--   3. Tabla DAVILA_calendar_events (el calendario que muestra el dashboard)
--
-- Flujo de las 3 fases:
--   CREATE (pre-reserva)     → GCal evento "pre-reserva" + fila en DAVILA_calendar_events + fila en pre_reservas (expira 40 min)
--   CRON / CANCELAR          → borra el evento GCal y la fila del dashboard, marca expirado/cancelado
--   calendario_agendar       → enriquece GCal + dashboard (cita real), inserta paciente en PacientesBDwppDAVILA, marca confirmado
-- ══════════════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────────────────
-- 1. pre_reservas (estructura final — 4 parámetros, sin datos personales)
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pre_reservas (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  celular             TEXT NOT NULL,
  pre_reserva_id      TEXT UNIQUE NOT NULL,
  calendar_event_id   TEXT,                       -- evento en Google Calendar
  fecha               DATE NOT NULL,
  hora                TEXT NOT NULL,
  estado              TEXT NOT NULL DEFAULT 'pre_reservado'
                      CHECK (estado IN ('pre_reservado','pagado','confirmado','expirado','cancelado')),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  expires_at          TIMESTAMPTZ NOT NULL,
  pagado_en           TIMESTAMPTZ,
  confirmado_en       TIMESTAMPTZ,
  cancelado_en        TIMESTAMPTZ
);

-- 2. Columna que enlaza la pre-reserva con la fila del calendario del dashboard
ALTER TABLE public.pre_reservas
  ADD COLUMN IF NOT EXISTS dashboard_event_id BIGINT;

-- Limpieza por si la tabla venía de la versión anterior con columnas de más
ALTER TABLE public.pre_reservas
  DROP COLUMN IF EXISTS metadata,
  DROP COLUMN IF EXISTS duracion_min;

-- RLS pre_reservas
ALTER TABLE public.pre_reservas ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "service_all_pre_reservas" ON public.pre_reservas
    FOR ALL TO service_role USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "anon_select_pre_reservas" ON public.pre_reservas
    FOR SELECT TO anon USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_pre_reservas_celular_estado ON public.pre_reservas (celular, estado);
CREATE INDEX IF NOT EXISTS idx_pre_reservas_estado_expires ON public.pre_reservas (estado, expires_at) WHERE estado = 'pre_reservado';


-- ─────────────────────────────────────────────────────────────────────────
-- 3. DAVILA_calendar_events (el calendario que renderiza el dashboard)
--    Columnas que el dashboard (pages/pruebas/MiguelDavila.vue) ya lee/escribe:
--      date, time, subject, description, procedure_id,
--      client_name, client_surname, client_dni, client_phone, client_email,
--      event_reason
--    + columnas extra para enlazar con la pre-reserva y su estado.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public."DAVILA_calendar_events" (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT timezone('utc', now()),

  -- Campos que usa el dashboard
  date            TEXT,         -- "YYYY-MM-DD"
  time            TEXT,         -- "HH:MM"
  subject         TEXT,
  description     TEXT,
  procedure_id    TEXT,
  client_name     TEXT,
  client_surname  TEXT,
  client_dni      TEXT,
  client_phone    TEXT,
  client_email    TEXT,
  event_reason    TEXT,

  -- Enlace con la pre-reserva / Google Calendar + estado
  pre_reserva_id    TEXT,        -- pre_xxxx (link a pre_reservas.pre_reserva_id)
  calendar_event_id TEXT,        -- mismo id del evento en Google Calendar
  estado            TEXT DEFAULT 'pre_reservado'
                    CHECK (estado IS NULL OR estado IN ('pre_reservado','confirmado','cancelado','expirado'))
);

ALTER TABLE public."DAVILA_calendar_events" ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "service_all_DAVILA_calendar_events" ON public."DAVILA_calendar_events"
    FOR ALL TO service_role USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "anon_all_DAVILA_calendar_events" ON public."DAVILA_calendar_events"
    FOR ALL TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "idx_DAVILA_calendar_events_date"     ON public."DAVILA_calendar_events" (date);
CREATE INDEX IF NOT EXISTS "idx_DAVILA_calendar_events_prereserva" ON public."DAVILA_calendar_events" (pre_reserva_id);

-- Si la tabla ya existía sin las columnas de enlace, agregarlas:
ALTER TABLE public."DAVILA_calendar_events"
  ADD COLUMN IF NOT EXISTS pre_reserva_id    TEXT,
  ADD COLUMN IF NOT EXISTS calendar_event_id TEXT,
  ADD COLUMN IF NOT EXISTS estado            TEXT;


-- ══════════════════════════════════════════════════════════════════════════
-- Verificación
-- ══════════════════════════════════════════════════════════════════════════
SELECT 'pre_reservas' AS tabla, count(*) AS columnas
FROM information_schema.columns WHERE table_schema='public' AND table_name='pre_reservas'
UNION ALL
SELECT 'DAVILA_calendar_events', count(*)
FROM information_schema.columns WHERE table_schema='public' AND table_name='DAVILA_calendar_events';
