-- ══════════════════════════════════════════════════════════════════════════
-- ECS (Estás Con Suerte) — Schema base
-- Replica las tablas core de Healup, adaptado al modelo de suscripciones/sorteos.
--
-- Equivalencias con Healup:
--   PacientesBDwppHEALUP   →  SuscriptoresBDwppECS
--   healup_calendar_events →  ecs_calendar_events
--   egresos_healup         →  egresos_ecs
--   healup_cita_pagos      →  ecs_cita_pagos
--
-- NO se crean tablas que no aplican a ECS:
--   ❌ healup_procedures        (ECS tiene planes en su propio sistema)
--   ❌ healup_stock_*           (ECS no maneja insumos)
--   ❌ healup_medical_history   (ECS no es clínica)
--   ❌ healup_working_hours     (ECS no agenda como clínica)
--   ❌ *BDfbig* (solo canal WhatsApp por ahora)
--
-- Idempotente: se puede correr múltiples veces sin romper nada.
-- ══════════════════════════════════════════════════════════════════════════


-- ──────────────────────────────────────────────────────────────────────────
-- 1. SuscriptoresBDwppECS
--    Equivalente a PacientesBDwppHEALUP — pero acá son SUSCRIPTORES
--    activos a un plan de sorteos (La Fija, Medio Pituco, Pituco, etc.)
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public."SuscriptoresBDwppECS" (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at              TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,

  -- Identificación del cliente
  nombre                  TEXT,
  apellido                TEXT,
  numero                  TEXT,                       -- WhatsApp / Yape (9 dígitos)
  dni                     TEXT,
  email                   TEXT,

  -- Datos del plan suscrito
  plan_nombre             TEXT,                       -- "La Fija" (humano)
  plan_key                TEXT,                       -- "LA_FIJA" (slug ECS)
  monto                   NUMERIC(10,2),              -- precio mensual en soles
  metodo_pago             TEXT,                       -- Yape | Tarjeta | Transferencia ...

  -- Trazabilidad de la suscripción (en sistema ECS y Monnet)
  ecs_subscription_id     BIGINT,                     -- ID interno en api.estasconsuerte.com.pe
  monnet_subscription_id  BIGINT,                     -- ID en Monnet
  operation_number        TEXT,                       -- FK a ecs_pagos_monnet.operation_number

  -- Fechas clave
  fecha_suscripcion       TIMESTAMPTZ,                -- cuando se autorizó la suscripción
  fecha_proxima_cobranza  TIMESTAMPTZ,                -- próximo cobro recurrente
  fecha_cancelacion       TIMESTAMPTZ,

  -- Estado del suscriptor
  estado                  TEXT DEFAULT 'pendiente',

  -- Origen del lead (si vino de la tabla de leads WhatsApp)
  lead_origen_id          BIGINT,                     -- referencia opcional a GeneralBDwppECS

  -- Notas libres
  notas                   TEXT,

  CONSTRAINT "SuscriptoresBDwppECS_estado_check"
    CHECK (estado IS NULL OR estado IN ('pendiente','activa','pausada','cancelada','expirada','fallida'))
);

ALTER TABLE public."SuscriptoresBDwppECS" ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "anon_all_SuscriptoresBDwppECS" ON public."SuscriptoresBDwppECS"
    TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "idx_SuscriptoresBDwppECS_numero"        ON public."SuscriptoresBDwppECS" (numero);
CREATE INDEX IF NOT EXISTS "idx_SuscriptoresBDwppECS_estado"        ON public."SuscriptoresBDwppECS" (estado);
CREATE INDEX IF NOT EXISTS "idx_SuscriptoresBDwppECS_plan_key"      ON public."SuscriptoresBDwppECS" (plan_key);
CREATE INDEX IF NOT EXISTS "idx_SuscriptoresBDwppECS_subscription"  ON public."SuscriptoresBDwppECS" (monnet_subscription_id);
CREATE INDEX IF NOT EXISTS "idx_SuscriptoresBDwppECS_op_number"     ON public."SuscriptoresBDwppECS" (operation_number);

COMMENT ON TABLE  public."SuscriptoresBDwppECS"        IS 'Clientes que se suscribieron via WhatsApp a un plan de ECS. Equivalente a PacientesBDwppHEALUP.';
COMMENT ON COLUMN public."SuscriptoresBDwppECS".numero IS 'Teléfono Yape (9 dígitos sin código de país).';
COMMENT ON COLUMN public."SuscriptoresBDwppECS".estado IS 'pendiente | activa | pausada | cancelada | expirada | fallida';


-- ──────────────────────────────────────────────────────────────────────────
-- 2. ecs_calendar_events
--    Equivalente a healup_calendar_events — para ECS usado en:
--      - Sorteos programados
--      - Llamadas de seguimiento / renovación
--      - Recordatorios de cobro
--      - Eventos administrativos
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ecs_calendar_events (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at              TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,

  -- Fecha y hora del evento (acepta DD-MM-YYYY del agente IA y YYYY-MM-DD manual)
  date                    TEXT,
  time                    TEXT,
  fecha_iso               TIMESTAMPTZ,                 -- normalizado para queries

  -- Cliente / suscriptor asociado (si aplica)
  client_name             TEXT,
  client_surname          TEXT,
  client_phone            TEXT,
  client_dni              TEXT,
  client_email            TEXT,
  suscriptor_id           BIGINT,                      -- FK opcional a SuscriptoresBDwppECS.id

  -- Tipo y detalles del evento
  tipo_evento             TEXT,                        -- sorteo | renovacion | llamada_seguimiento | cobro | otros
  titulo                  TEXT,
  descripcion             TEXT,
  plan_nombre             TEXT,                        -- si el evento es relativo a un plan
  notas                   TEXT,

  -- Estado del evento (mismo set que Healup)
  estado                  TEXT,
  estado_actualizado_en   TIMESTAMPTZ,
  estado_actualizado_por  TEXT,
  reagendado_a_id         BIGINT REFERENCES public.ecs_calendar_events(id) ON DELETE SET NULL,

  -- Trazabilidad de cobro (si aplica al evento)
  cobro_completado        BOOLEAN DEFAULT FALSE,
  monto_cobrado           NUMERIC(10,2),
  metodo_pago             TEXT,
  comprobante_id          BIGINT,                      -- FK opcional a comprobantes_pse

  CONSTRAINT ecs_calendar_events_estado_check
    CHECK (estado IS NULL OR estado IN ('RESERVADA','EN_CURSO','FINALIZADA','NO_SHOW','REAGENDADA','CANCELADA')),
  CONSTRAINT ecs_calendar_events_tipo_check
    CHECK (tipo_evento IS NULL OR tipo_evento IN ('sorteo','renovacion','llamada_seguimiento','cobro','reunion','otros'))
);

ALTER TABLE public.ecs_calendar_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "anon_all_ecs_calendar_events" ON public.ecs_calendar_events
    TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_ecs_calendar_events_date        ON public.ecs_calendar_events (date);
CREATE INDEX IF NOT EXISTS idx_ecs_calendar_events_fecha_iso   ON public.ecs_calendar_events (fecha_iso);
CREATE INDEX IF NOT EXISTS idx_ecs_calendar_events_estado      ON public.ecs_calendar_events (estado)        WHERE estado IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ecs_calendar_events_tipo        ON public.ecs_calendar_events (tipo_evento)   WHERE tipo_evento IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ecs_calendar_events_phone       ON public.ecs_calendar_events (client_phone);
CREATE INDEX IF NOT EXISTS idx_ecs_calendar_events_suscriptor  ON public.ecs_calendar_events (suscriptor_id) WHERE suscriptor_id IS NOT NULL;

COMMENT ON TABLE  public.ecs_calendar_events             IS 'Calendario de ECS: sorteos, renovaciones, llamadas, cobros.';
COMMENT ON COLUMN public.ecs_calendar_events.date        IS 'Fecha en DD-MM-YYYY (agente IA) o YYYY-MM-DD (manual). Usar fecha_iso para queries.';
COMMENT ON COLUMN public.ecs_calendar_events.tipo_evento IS 'sorteo | renovacion | llamada_seguimiento | cobro | reunion | otros';


-- ──────────────────────────────────────────────────────────────────────────
-- 3. egresos_ecs
--    Equivalente a egresos_healup — contabilidad de gastos.
--    Categorías adaptadas al negocio de sorteos:
--      PREMIOS, MARKETING, PLATAFORMAS, OPERATIVOS, SUELDOS, LEGAL, OTROS
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.egresos_ecs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  fecha           DATE        DEFAULT CURRENT_DATE,

  -- Datos del egreso (campos legacy compatibles con Healup)
  tipo_egreso     TEXT,
  nombre          TEXT,
  precio          NUMERIC(10,2),
  cantidad        INTEGER     DEFAULT 1,

  -- Categorización (mismo patrón que healup_egresos_categorias)
  categoria       TEXT,
  metodo_pago     TEXT,
  referencia      TEXT,

  -- Detalles de producto/servicio
  producto        TEXT,
  unidad          TEXT,
  precio_unitario NUMERIC(10,2),

  -- Soft delete
  deleted_at      TIMESTAMPTZ,
  descartado      BOOLEAN DEFAULT FALSE,

  CONSTRAINT egresos_ecs_categoria_check
    CHECK (categoria IS NULL OR categoria IN (
      'PREMIOS','MARKETING','PLATAFORMAS','OPERATIVOS','SUELDOS','LEGAL','OTROS'
    )),
  CONSTRAINT egresos_ecs_metodo_pago_check
    CHECK (metodo_pago IS NULL OR metodo_pago IN (
      'EFECTIVO','YAPE','PLIN','TRANSFERENCIA','TARJETA_CREDITO','TARJETA_DEBITO','QR'
    ))
);

ALTER TABLE public.egresos_ecs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "anon_all_egresos_ecs" ON public.egresos_ecs
    TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_egresos_ecs_categoria   ON public.egresos_ecs (categoria)   WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_egresos_ecs_metodo_pago ON public.egresos_ecs (metodo_pago) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_egresos_ecs_fecha       ON public.egresos_ecs (fecha DESC)  WHERE deleted_at IS NULL;

COMMENT ON TABLE  public.egresos_ecs           IS 'Contabilidad de egresos de ECS. Equivalente a egresos_healup.';
COMMENT ON COLUMN public.egresos_ecs.categoria IS 'PREMIOS | MARKETING | PLATAFORMAS | OPERATIVOS | SUELDOS | LEGAL | OTROS';


-- ──────────────────────────────────────────────────────────────────────────
-- 4. ecs_cita_pagos
--    Equivalente a healup_cita_pagos — pagos multi-método por evento.
--    Útil para registrar cobros manuales (efectivo, transferencia directa)
--    de eventos del calendario que no pasaron por Monnet.
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ecs_cita_pagos (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at       TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  event_id         BIGINT,                            -- FK opcional a ecs_calendar_events.id
  suscriptor_id    BIGINT,                            -- FK opcional a SuscriptoresBDwppECS.id
  comprobante_id   BIGINT,                            -- FK opcional a comprobantes_pse
  metodo_pago      TEXT NOT NULL,
  monto            NUMERIC(10,2) NOT NULL,
  notas            TEXT
);

ALTER TABLE public.ecs_cita_pagos ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "anon_all_ecs_cita_pagos" ON public.ecs_cita_pagos
    TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_ecs_cita_pagos_event_id      ON public.ecs_cita_pagos (event_id)      WHERE event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ecs_cita_pagos_suscriptor_id ON public.ecs_cita_pagos (suscriptor_id) WHERE suscriptor_id IS NOT NULL;

COMMENT ON TABLE  public.ecs_cita_pagos             IS 'Pagos parciales/multi-método por evento del calendario ECS.';
COMMENT ON COLUMN public.ecs_cita_pagos.metodo_pago IS 'Yape | Plin | Efectivo | Transferencia | Tarjeta';


-- ══════════════════════════════════════════════════════════════════════════
-- Verificación rápida (debe devolver las 4 tablas con sus columnas)
-- ══════════════════════════════════════════════════════════════════════════
SELECT table_name, COUNT(*) AS columnas
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN ('SuscriptoresBDwppECS', 'ecs_calendar_events', 'egresos_ecs', 'ecs_cita_pagos')
GROUP BY table_name
ORDER BY table_name;


-- ══════════════════════════════════════════════════════════════════════════
-- ROLLBACK (correr solo si querés deshacer toda la migración):
--
-- DROP TABLE IF EXISTS public.ecs_cita_pagos      CASCADE;
-- DROP TABLE IF EXISTS public.egresos_ecs         CASCADE;
-- DROP TABLE IF EXISTS public.ecs_calendar_events CASCADE;
-- DROP TABLE IF EXISTS public."SuscriptoresBDwppECS" CASCADE;
-- ══════════════════════════════════════════════════════════════════════════
