-- ══════════════════════════════════════════════════════════════════════════
-- FORMS — Firma digital
--
-- Agrega dos tipos de pregunta al sistema de formularios:
--
--   • 'firma'     → pad para firmar con el dedo. La respuesta es un dataURL
--                   base64 del PNG, guardado dentro de `answers`.
--
--   • 'firmante'  → desplegable de personas (ej. los técnicos de Gatwick).
--                   Cada una tiene su firma guardada acá. Al elegir una, el
--                   documento generado sale con SU firma.
--
-- Sobre `firmante`: el navegador solo manda el id del firmante. El servidor
-- resuelve ese id contra esta tabla y guarda una *copia* de la firma dentro
-- de la respuesta. Dos razones:
--   1. Seguridad: el cliente nunca recibe ni puede falsificar la imagen.
--   2. Inmutabilidad: si mañana el técnico cambia su firma, los informes ya
--      emitidos conservan la que estaba vigente cuando se firmaron.
-- ══════════════════════════════════════════════════════════════════════════


CREATE TABLE IF NOT EXISTS public.form_signatories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  updated_at  TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,

  -- Empresa dueña del firmante. Mismos valores que forms.company_id
  company_id  TEXT NOT NULL,

  nombre      TEXT NOT NULL,
  cargo       TEXT,               -- ej. 'Técnico', 'Supervisor'
  documento   TEXT,               -- DNI / CE, opcional

  -- Firma en dataURL base64 (image/png). NULL = firmante sin firma cargada:
  -- se puede elegir igual y el documento sale solo con el nombre.
  firma       TEXT,

  activo      BOOLEAN DEFAULT TRUE NOT NULL,
  orden       INT DEFAULT 0 NOT NULL,

  CONSTRAINT form_signatories_company_id_check
    CHECK (company_id IN (
      'healup','brada','alef','alegrated','clinicaarroyo','origitec',
      'solari','skip','estasconsuerte','estetikamedika','davila','gatwick'
    ))
);

ALTER TABLE public.form_signatories ENABLE ROW LEVEL SECURITY;

-- Solo el servidor toca esta tabla. La página pública NO lee de acá
-- directamente: el endpoint /api/forms/public/[slug] le entrega la lista ya
-- filtrada y SIN el campo `firma`, para no exponer las firmas a cualquiera
-- que abra el link del formulario.
DO $$ BEGIN
  CREATE POLICY "service_all_form_signatories" ON public.form_signatories
    FOR ALL TO service_role
    USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_form_signatories_company
  ON public.form_signatories (company_id) WHERE activo = true;

COMMENT ON TABLE  public.form_signatories IS
  'Personas que pueden firmar un formulario, con su firma guardada. Usado por las preguntas de tipo "firmante".';
COMMENT ON COLUMN public.form_signatories.firma IS
  'dataURL base64 (image/png) de la firma. Nunca se expone al formulario público.';


-- Trigger de updated_at (reusa la función creada en forms_schema.sql)
DROP TRIGGER IF EXISTS form_signatories_updated_at_trigger ON public.form_signatories;
CREATE TRIGGER form_signatories_updated_at_trigger
  BEFORE UPDATE ON public.form_signatories
  FOR EACH ROW
  EXECUTE FUNCTION update_forms_updated_at();


-- ─────────────────────────────────────────────────────────────────────────
-- Semilla: los técnicos de Gatwick, sin firma todavía.
-- Se cargan las firmas desde el dashboard (Formularios → Firmantes).
-- ─────────────────────────────────────────────────────────────────────────
INSERT INTO public.form_signatories (company_id, nombre, cargo, orden)
SELECT 'gatwick', v.nombre, 'Técnico', v.orden
FROM (VALUES
  ('Técnico 1', 1),
  ('Técnico 2', 2)
) AS v(nombre, orden)
WHERE NOT EXISTS (
  SELECT 1 FROM public.form_signatories WHERE company_id = 'gatwick'
);


-- ═══════════════════════════════════════════════════════════════════════════
-- VERIFICACIÓN
-- ═══════════════════════════════════════════════════════════════════════════
SELECT id, company_id, nombre, cargo, (firma IS NOT NULL) AS tiene_firma, activo
FROM public.form_signatories
ORDER BY company_id, orden;


-- ═══════════════════════════════════════════════════════════════════════════
-- ROLLBACK:
-- DROP TABLE IF EXISTS public.form_signatories CASCADE;
-- ═══════════════════════════════════════════════════════════════════════════
