-- ══════════════════════════════════════════════════════════════════════════
-- FORMS — Sistema de formularios tipo Google Forms
--
-- Diseño:
--   • Tabla global `forms` con la definición de cada formulario (preguntas
--     en JSONB).
--   • Una tabla `form_responses_<empresa>` por empresa con las respuestas.
--     Esto aísla los datos de cada cliente y facilita exportes selectivos.
--
-- Permisos:
--   • Lectura/escritura de la tabla `forms`: solo desde el servidor (service_role)
--   • Lectura de form definition (slug público): policy SELECT TO anon
--   • Inserción de respuestas: policy INSERT TO anon (cualquiera puede submit
--     conociendo el slug)
--   • Lectura de respuestas: solo desde el servidor (service_role) que
--     valida cookie de sesión y rol antes de servir.
-- ══════════════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────────────────
-- TABLA GLOBAL: forms
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.forms (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  updated_at   TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,

  -- Identificador único usado en la URL pública (/forms/<slug>)
  slug         TEXT UNIQUE NOT NULL,

  -- Información del form
  title        TEXT NOT NULL,
  description  TEXT,

  -- A qué empresa pertenece: 'healup', 'gatwick', 'brada', etc.
  -- Determina en qué tabla form_responses_<empresa> se guardan las respuestas
  company_id   TEXT NOT NULL,

  -- Esquema de las preguntas — array de objetos:
  --   { id, type, label, required, options?, placeholder? }
  -- type: 'short' | 'long' | 'checkbox' | 'radio' | 'date' | 'email' | 'phone'
  fields       JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Quién lo creó (email del superadmin)
  created_by   TEXT,

  -- Si está activo (se puede llenar). Si false, la URL pública devuelve "form cerrado"
  active       BOOLEAN DEFAULT TRUE,

  -- Configuración opcional
  redirect_url TEXT,                            -- a dónde redirigir después de submit (opcional)
  thanks_text  TEXT DEFAULT '¡Gracias por completar el formulario!',

  CONSTRAINT forms_company_id_check
    CHECK (company_id IN (
      'healup','brada','alef','alegrated','clinicaarroyo','origitec',
      'solari','skip','estasconsuerte','estetikamedika','davila','gatwick'
    ))
);

ALTER TABLE public.forms ENABLE ROW LEVEL SECURITY;

-- Policy: cualquiera puede LEER un form activo (necesario para la página pública)
DO $$ BEGIN
  CREATE POLICY "anon_read_active_forms" ON public.forms
    FOR SELECT TO anon
    USING (active = true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Policy: service_role tiene acceso total
DO $$ BEGIN
  CREATE POLICY "service_all_forms" ON public.forms
    FOR ALL TO service_role
    USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_forms_slug       ON public.forms (slug);
CREATE INDEX IF NOT EXISTS idx_forms_company_id ON public.forms (company_id);
CREATE INDEX IF NOT EXISTS idx_forms_active     ON public.forms (active) WHERE active = true;

COMMENT ON TABLE  public.forms          IS 'Definición de formularios públicos tipo Google Forms';
COMMENT ON COLUMN public.forms.fields   IS 'Array JSONB con la definición de cada pregunta: { id, type, label, required, options? }';
COMMENT ON COLUMN public.forms.company_id IS 'A qué empresa pertenece el form. Determina la tabla form_responses_<empresa>';


-- ─────────────────────────────────────────────────────────────────────────
-- TABLAS DE RESPUESTAS — una por empresa
-- ─────────────────────────────────────────────────────────────────────────
-- Se generan dinámicamente con el siguiente DO block para no repetir 12 veces
-- la misma estructura. Si en el futuro hay una nueva empresa, agregar su slug
-- al array y volver a correr este bloque (es idempotente).

DO $$
DECLARE
  empresa TEXT;
  empresas TEXT[] := ARRAY[
    'healup', 'brada', 'alef', 'alegrated', 'clinicaarroyo', 'origitec',
    'solari', 'skip', 'estasconsuerte', 'estetikamedika', 'davila', 'gatwick'
  ];
BEGIN
  FOREACH empresa IN ARRAY empresas LOOP
    -- Crear tabla form_responses_<empresa>
    EXECUTE format('
      CREATE TABLE IF NOT EXISTS public.form_responses_%I (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        submitted_at  TIMESTAMPTZ DEFAULT timezone(''utc'', now()) NOT NULL,
        form_id       BIGINT NOT NULL REFERENCES public.forms(id) ON DELETE CASCADE,

        -- Respuestas: objeto JSONB { field_id: value }
        answers       JSONB NOT NULL DEFAULT ''{}''::jsonb,

        -- Trazabilidad
        ip_address    TEXT,
        user_agent    TEXT,
        referrer      TEXT
      )', empresa);

    -- Habilitar RLS
    EXECUTE format('ALTER TABLE public.form_responses_%I ENABLE ROW LEVEL SECURITY', empresa);

    -- Policy: anon puede INSERT (para que el form público guarde respuestas)
    EXECUTE format($pol$
      DO $do$ BEGIN
        CREATE POLICY "anon_insert_form_responses_%1$s" ON public.form_responses_%1$I
          FOR INSERT TO anon
          WITH CHECK (true);
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $do$
    $pol$, empresa);

    -- Policy: service_role tiene acceso total
    EXECUTE format($pol$
      DO $do$ BEGIN
        CREATE POLICY "service_all_form_responses_%1$s" ON public.form_responses_%1$I
          FOR ALL TO service_role
          USING (true) WITH CHECK (true);
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $do$
    $pol$, empresa);

    -- Índices
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_form_responses_%1$s_form_id ON public.form_responses_%1$I (form_id)', empresa);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_form_responses_%1$s_submitted ON public.form_responses_%1$I (submitted_at DESC)', empresa);

    -- Comentario
    EXECUTE format('COMMENT ON TABLE public.form_responses_%I IS ''Respuestas de formularios de la empresa %s''', empresa, empresa);
  END LOOP;
END $$;


-- ─────────────────────────────────────────────────────────────────────────
-- Trigger para auto-actualizar updated_at en forms
-- ─────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_forms_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS forms_updated_at_trigger ON public.forms;
CREATE TRIGGER forms_updated_at_trigger
  BEFORE UPDATE ON public.forms
  FOR EACH ROW
  EXECUTE FUNCTION update_forms_updated_at();


-- ═══════════════════════════════════════════════════════════════════════════
-- VERIFICACIÓN — debe devolver 13 tablas (forms + 12 form_responses_<empresa>)
-- ═══════════════════════════════════════════════════════════════════════════
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND (table_name = 'forms' OR table_name LIKE 'form_responses_%')
ORDER BY table_name;


-- ═══════════════════════════════════════════════════════════════════════════
-- ROLLBACK (sólo si querés deshacer):
--
-- DROP TABLE IF EXISTS public.form_responses_gatwick        CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_davila         CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_estetikamedika CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_estasconsuerte CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_skip           CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_solari         CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_origitec       CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_clinicaarroyo  CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_alegrated      CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_alef           CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_brada          CASCADE;
-- DROP TABLE IF EXISTS public.form_responses_healup         CASCADE;
-- DROP TABLE IF EXISTS public.forms                         CASCADE;
-- DROP FUNCTION IF EXISTS update_forms_updated_at();
-- ═══════════════════════════════════════════════════════════════════════════
