-- =====================================================================
-- 2.1 Cita 1—N CitaProcedimiento  +  2.2 Cita 1—N Pago
-- =====================================================================
-- Refactor sin pérdida: las tablas legacy (precio, precio_tratamiento,
-- procedimiento TEXT, metodo_de_pago, procedure_id en cita) se mantienen
-- intactas. Las nuevas tablas viven en paralelo y la UI nueva (detrás de
-- feature flag) escribe en ambas hasta que estabilicemos.
--
-- Modelo:
--   healup_cita_procedimientos
--     id, cita_id (FK), procedure_id (FK catálogo), nombre_libre,
--     cantidad, precio_unitario, descuento, total, notas, created_at
--
--   healup_cita_pagos
--     id, cita_id (FK), metodo, monto, referencia, comprobante_tipo,
--     comprobante_numero, comprobante_fecha, comprobante_emitido_por,
--     comprobante_id (FK opcional a comprobantes_pse), created_at
--
-- Idempotente y reversible.
-- =====================================================================

-- ------------ 2.1 — múltiples procedimientos por cita ------------
CREATE TABLE IF NOT EXISTS public.healup_cita_procedimientos (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  cita_id          BIGINT NOT NULL REFERENCES public.healup_calendar_events(id) ON DELETE CASCADE,
  procedure_id     BIGINT REFERENCES public.healup_procedures(id) ON DELETE SET NULL,
  nombre_libre     TEXT,                          -- override si no está en catálogo
  cantidad         NUMERIC(10,2) DEFAULT 1,
  precio_unitario  NUMERIC(10,2) DEFAULT 0,       -- precio sin IGV (valor_unitario)
  descuento        NUMERIC(10,2) DEFAULT 0,       -- descuento en S/ sobre la línea
  total            NUMERIC(10,2) DEFAULT 0,       -- = (cantidad * precio_unitario - descuento) * 1.18
  notas            TEXT
);

CREATE INDEX IF NOT EXISTS idx_cita_proc_cita ON public.healup_cita_procedimientos (cita_id);

-- ------------ 2.2 — múltiples pagos por cita ------------
CREATE TABLE IF NOT EXISTS public.healup_cita_pagos (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  cita_id                BIGINT NOT NULL REFERENCES public.healup_calendar_events(id) ON DELETE CASCADE,
  metodo                 TEXT NOT NULL,           -- EFECTIVO | YAPE | PLIN | TRANSFERENCIA | TARJETA_CREDITO | QR
  monto                  NUMERIC(10,2) NOT NULL,
  referencia             TEXT,                    -- # voucher, # operación
  -- 2.8 — comprobante asociado a este pago
  comprobante_tipo       TEXT,                    -- BOLETA | FACTURA | NINGUNO
  comprobante_serie      TEXT,
  comprobante_numero     BIGINT,
  comprobante_fecha      DATE,
  comprobante_emitido_por TEXT,                   -- email del usuario que emitió
  comprobante_id         BIGINT REFERENCES public.comprobantes_pse(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_cita_pagos_cita    ON public.healup_cita_pagos (cita_id);
CREATE INDEX IF NOT EXISTS idx_cita_pagos_metodo  ON public.healup_cita_pagos (metodo);
CREATE INDEX IF NOT EXISTS idx_cita_pagos_sin_comp ON public.healup_cita_pagos (id)
  WHERE comprobante_tipo IS NULL OR comprobante_tipo = 'NINGUNO';

ALTER TABLE public.healup_cita_pagos
  DROP CONSTRAINT IF EXISTS healup_cita_pagos_metodo_check;
ALTER TABLE public.healup_cita_pagos
  ADD CONSTRAINT healup_cita_pagos_metodo_check
  CHECK (metodo IN ('EFECTIVO','YAPE','PLIN','TRANSFERENCIA','TARJETA_CREDITO','QR'));

ALTER TABLE public.healup_cita_pagos
  DROP CONSTRAINT IF EXISTS healup_cita_pagos_comprobante_tipo_check;
ALTER TABLE public.healup_cita_pagos
  ADD CONSTRAINT healup_cita_pagos_comprobante_tipo_check
  CHECK (comprobante_tipo IS NULL OR comprobante_tipo IN ('BOLETA','FACTURA','NINGUNO'));

COMMENT ON TABLE public.healup_cita_procedimientos IS 'Múltiples procedimientos por cita (ticket de mayo 2026).';
COMMENT ON TABLE public.healup_cita_pagos          IS 'Múltiples pagos por cita + tracking de comprobante (boleta/factura).';

-- ------------ Backfill: una fila por cita_id desde data legacy ------------
-- Solo corre si las tablas nuevas están vacías (idempotente).
DO $$
DECLARE
  n_proc INTEGER;
  n_pago INTEGER;
BEGIN
  SELECT COUNT(*) INTO n_proc FROM public.healup_cita_procedimientos;
  SELECT COUNT(*) INTO n_pago FROM public.healup_cita_pagos;

  IF n_proc = 0 THEN
    INSERT INTO public.healup_cita_procedimientos (cita_id, procedure_id, nombre_libre, cantidad, precio_unitario, total)
    SELECT
      e.id,
      CASE WHEN e.procedure_id ~ '^\d+$' THEN e.procedure_id::BIGINT ELSE NULL END,
      e.subject,
      1,
      0, 0
    FROM public.healup_calendar_events e
    WHERE e.procedure_id IS NOT NULL OR e.subject IS NOT NULL;
    RAISE NOTICE 'Backfill cita_procedimientos: % filas', (SELECT COUNT(*) FROM public.healup_cita_procedimientos);
  END IF;

  IF n_pago = 0 THEN
    INSERT INTO public.healup_cita_pagos (cita_id, metodo, monto, referencia, comprobante_tipo, comprobante_serie, comprobante_numero, comprobante_id)
    SELECT
      e.id,
      UPPER(COALESCE(e.metodo_reserva, 'EFECTIVO'))::TEXT,
      COALESCE(e.monto_reserva, 0),
      NULL,
      CASE WHEN e.boleta_consulta_numero IS NOT NULL THEN 'BOLETA' ELSE NULL END,
      e.boleta_consulta_serie,
      e.boleta_consulta_numero,
      e.boleta_consulta_id
    FROM public.healup_calendar_events e
    WHERE e.monto_reserva IS NOT NULL AND e.monto_reserva > 0;
    RAISE NOTICE 'Backfill cita_pagos: % filas', (SELECT COUNT(*) FROM public.healup_cita_pagos);
  END IF;
END $$;
