-- =====================================================================
-- Healup — Multi-pago por cita (1:N metodos de pago por atencion)
-- =====================================================================
-- Permite registrar pagos divididos: ej. S/500 Yape + S/200 Transferencia + S/50 Efectivo
-- Cada fila es un metodo de pago parcial. La suma de montos debe igualar el total cobrado.
--
-- Aplicar en Supabase SQL editor.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.healup_cita_pagos (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at       TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  event_id         BIGINT,
  comprobante_id   BIGINT,
  metodo_pago      TEXT NOT NULL,
  monto            NUMERIC(10,2) NOT NULL,
  notas            TEXT
);

ALTER TABLE public.healup_cita_pagos ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "anon_all_healup_cita_pagos" ON public.healup_cita_pagos TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_healup_cita_pagos_event_id
  ON healup_cita_pagos (event_id)
  WHERE event_id IS NOT NULL;

COMMENT ON TABLE healup_cita_pagos IS 'Pagos parciales por atencion medica — permite multi-metodo';
COMMENT ON COLUMN healup_cita_pagos.metodo_pago IS 'Yape | Plin | Efectivo | Transferencia | Tarjeta';
COMMENT ON COLUMN healup_cita_pagos.monto IS 'Monto parcial en soles';
