-- =====================================================================
-- audit_log: registro de cambios sensibles en Healup
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.healup_audit_log (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  user_email    TEXT,
  user_role     TEXT,
  entidad       TEXT NOT NULL,
  entidad_id    TEXT,
  accion        TEXT NOT NULL,
  campo         TEXT,
  valor_antes   JSONB,
  valor_despues JSONB,
  notas         TEXT
);

CREATE INDEX IF NOT EXISTS idx_healup_audit_log_entidad ON public.healup_audit_log (entidad, entidad_id);
CREATE INDEX IF NOT EXISTS idx_healup_audit_log_user    ON public.healup_audit_log (user_email, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_healup_audit_log_created ON public.healup_audit_log (created_at DESC);

-- ROLLBACK: DROP TABLE IF EXISTS public.healup_audit_log;
