-- =====================================================================
-- Audit log para Healup — registra cambios sensibles
-- =====================================================================
-- Captura: quién (usuario), cuándo (timestamp), qué cambió (entidad +
-- campo + valor antes/después).
--
-- Casos de uso:
--   - cita: cambio de estado (RESERVADA → FINALIZADA, etc.)
--   - cita: cambio de monto pagado / método de pago
--   - paciente: edición manual de nombre/DNI/teléfono
--   - egreso: edición o soft-delete
--
-- La inserción la hace la UI (cliente) llamando a este endpoint.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.healup_audit_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  user_email  TEXT,                                -- quién hizo el cambio
  user_role   TEXT,                                -- superadmin/admin/agente
  entidad     TEXT NOT NULL,                       -- 'cita', 'paciente', 'egreso', 'pago', etc.
  entidad_id  TEXT,                                -- id de la fila afectada (TEXT acepta UUID y BIGINT)
  accion      TEXT NOT NULL,                       -- 'create', 'update', 'soft_delete', 'state_change'
  campo       TEXT,                                -- nombre del campo modificado (si aplica)
  valor_antes JSONB,                               -- snapshot del valor anterior
  valor_despues JSONB,                             -- snapshot del valor nuevo
  notas       TEXT                                 -- contexto libre
);

CREATE INDEX IF NOT EXISTS idx_healup_audit_log_entidad
  ON public.healup_audit_log (entidad, entidad_id);
CREATE INDEX IF NOT EXISTS idx_healup_audit_log_user
  ON public.healup_audit_log (user_email, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_healup_audit_log_created
  ON public.healup_audit_log (created_at DESC);

COMMENT ON TABLE  public.healup_audit_log IS 'Registro de auditoría de cambios sensibles en Healup.';
COMMENT ON COLUMN public.healup_audit_log.accion IS 'create | update | soft_delete | state_change';
