-- =====================================================================
-- 2.9 Profesional / Cabina — separación de ingresos por doctora
-- =====================================================================
-- Tabla maestra de profesionales (doctora Valeria, doctora junior Jenny).
-- healup_calendar_events ya tiene `cabina` (cabina1/cabina2). Agregamos
-- `profesional_id` como FK explícita para reportes.
--
-- Idempotente y reversible.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.healup_profesionales (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  nombre      TEXT NOT NULL,
  apellido    TEXT,
  cabina      TEXT,                              -- cabina1 / cabina2
  rol         TEXT,                              -- doctora_principal | doctora_junior | cosmiatra
  email       TEXT,
  activo      BOOLEAN DEFAULT TRUE
);

ALTER TABLE healup_calendar_events
  ADD COLUMN IF NOT EXISTS profesional_id BIGINT REFERENCES public.healup_profesionales(id) ON DELETE SET NULL;

-- Seed inicial: Valeria (cabina1) y Jenny (cabina2)
INSERT INTO public.healup_profesionales (nombre, apellido, cabina, rol, activo)
SELECT * FROM (VALUES
  ('Valeria', NULL, 'cabina1', 'doctora_principal', true),
  ('Jenny',   NULL, 'cabina2', 'doctora_junior',    true)
) AS p(nombre, apellido, cabina, rol, activo)
WHERE NOT EXISTS (SELECT 1 FROM public.healup_profesionales);

-- Backfill: asignar profesional_id según cabina existente
UPDATE healup_calendar_events e
SET profesional_id = (
  SELECT id FROM public.healup_profesionales p
  WHERE p.cabina = e.cabina AND p.activo = true
  LIMIT 1
)
WHERE profesional_id IS NULL AND cabina IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_healup_calendar_events_profesional
  ON healup_calendar_events (profesional_id);
CREATE INDEX IF NOT EXISTS idx_healup_profesionales_cabina
  ON public.healup_profesionales (cabina) WHERE activo = true;

COMMENT ON TABLE  public.healup_profesionales IS 'Profesionales que atienden en Healup (doctoras y cosmiatra).';
COMMENT ON COLUMN healup_calendar_events.profesional_id IS 'FK al profesional asignado a la cita (default según cabina).';
