-- ══════════════════════════════════════════════════════════════════
-- HEALUP — Sistema de Control de Stock e Insumos
-- Ejecutar en: Supabase Dashboard → SQL Editor
-- ══════════════════════════════════════════════════════════════════

-- 1. Insumos / Items de inventario
CREATE TABLE IF NOT EXISTS public.healup_stock_items (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at       TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  nombre           TEXT NOT NULL,
  categoria        TEXT,
  unidad           TEXT NOT NULL DEFAULT 'unidad',
  cantidad_actual  NUMERIC DEFAULT 0,
  umbral_minimo    NUMERIC DEFAULT 5,
  costo_unitario   NUMERIC DEFAULT 0,
  proveedor        TEXT,
  notas            TEXT
);

-- 2. Movimientos de stock (entradas y salidas)
CREATE TABLE IF NOT EXISTS public.healup_stock_movements (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  stock_item_id  BIGINT REFERENCES public.healup_stock_items(id) ON DELETE CASCADE,
  tipo           TEXT NOT NULL CHECK (tipo IN ('entrada', 'salida', 'ajuste')),
  cantidad       NUMERIC NOT NULL,
  motivo         TEXT,
  event_id       BIGINT,
  procedure_id   BIGINT,
  notas          TEXT,
  registrado_por TEXT
);

-- 3. Recetas: insumos requeridos por procedimiento
CREATE TABLE IF NOT EXISTS public.healup_procedure_supplies (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  procedure_id    BIGINT NOT NULL,
  stock_item_id   BIGINT REFERENCES public.healup_stock_items(id) ON DELETE CASCADE,
  cantidad_usada  NUMERIC NOT NULL DEFAULT 1,
  unidad          TEXT,   -- ej: ml, cc, g, unidad, vial (puede diferir de la unidad del stock)
  notas           TEXT
);

-- Si la tabla ya existía sin la columna unidad, agrégala:
ALTER TABLE public.healup_procedure_supplies ADD COLUMN IF NOT EXISTS unidad TEXT;

-- ──────────────────────────────────────────────────────────────────
-- Función: descontar stock automáticamente al registrar un evento
-- Llamar manualmente desde el dashboard cuando se confirma un evento
-- ──────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.healup_descontar_insumos_procedimiento(
  p_procedure_id BIGINT,
  p_event_id     BIGINT,
  p_usuario      TEXT DEFAULT 'sistema'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT ps.stock_item_id, ps.cantidad_usada
    FROM healup_procedure_supplies ps
    WHERE ps.procedure_id = p_procedure_id
  LOOP
    -- Insertar movimiento de salida
    INSERT INTO healup_stock_movements
      (stock_item_id, tipo, cantidad, motivo, event_id, procedure_id, registrado_por)
    VALUES
      (r.stock_item_id, 'salida', r.cantidad_usada, 'procedimiento', p_event_id, p_procedure_id, p_usuario);

    -- Descontar del stock actual
    UPDATE healup_stock_items
    SET cantidad_actual = cantidad_actual - r.cantidad_usada
    WHERE id = r.stock_item_id;
  END LOOP;
END;
$$;

-- ──────────────────────────────────────────────────────────────────
-- Insumos base precargados (puedes ajustar según inventario real)
-- ──────────────────────────────────────────────────────────────────
INSERT INTO public.healup_stock_items (nombre, categoria, unidad, cantidad_actual, umbral_minimo, costo_unitario) VALUES
  ('Toxina Botulínica (Botox)', 'Medicina Estética', 'vial', 5, 2, 450.00),
  ('Ácido Hialurónico 1ml', 'Medicina Estética', 'jeringa', 8, 3, 180.00),
  ('Ácido Hialurónico 2ml', 'Medicina Estética', 'jeringa', 4, 2, 280.00),
  ('Enzimas Lipolíticas (Lipozim)', 'Lipo Papada', 'vial', 6, 2, 120.00),
  ('Exosomas Faciales', 'Tratamiento Médico', 'kit', 3, 2, 350.00),
  ('NCTF Filler', 'Tratamiento Médico', 'vial', 4, 2, 200.00),
  ('PRP Kit (tubos + centrifugadora use)', 'Tratamiento Médico', 'kit', 5, 3, 80.00),
  ('Sérum Vitamina C', 'Facial', 'ml', 200, 50, 0.50),
  ('Mascarilla Hidratante', 'Facial', 'unidad', 20, 5, 12.00),
  ('Ácido Hialurónico Tópico', 'Facial', 'ml', 150, 30, 0.30),
  ('Aguja 30G 1/2"', 'Consumible', 'caja x50', 3, 1, 25.00),
  ('Cánula 23G', 'Consumible', 'unidad', 10, 3, 8.00),
  ('Guantes nitrilo M', 'Consumible', 'caja x100', 5, 2, 35.00),
  ('Gasas estériles', 'Consumible', 'paquete x100', 8, 3, 12.00),
  ('Lidocaína tópica crema', 'Anestesia', 'tubo', 4, 2, 45.00),
  ('Gas CO2 (carboxiterapia)', 'Carboxiterapia', 'ml', 5000, 1000, 0.02),
  ('Ultrasound gel (HIFU)', 'HIFU', 'litro', 3, 1, 80.00)
ON CONFLICT DO NOTHING;

-- Verificar resultado
SELECT id, nombre, categoria, cantidad_actual, umbral_minimo, unidad FROM healup_stock_items ORDER BY categoria, nombre;
