-- =====================================================================
-- Remarketing Multi-tenant — Sistema de seguimiento y reactivacion
-- =====================================================================
-- Basado en estrategia DTI: temperatura x procedimiento x tiempo
-- Aplica a todas las empresas del dashboard ALEF.
-- Aplicar en Supabase SQL editor.
-- =====================================================================

-- Config por empresa (Chatwoot connection + cadencias)
CREATE TABLE IF NOT EXISTS public.remarketing_config (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at       TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  company_id       TEXT NOT NULL UNIQUE,
  chatwoot_account_id  INT NOT NULL,
  chatwoot_inbox_id    INT DEFAULT 1,
  cadencia_caliente_horas  INT DEFAULT 48,
  cadencia_tibio_dias      INT DEFAULT 5,
  cadencia_frio_dias       INT DEFAULT 30,
  activo           BOOLEAN DEFAULT true
);

ALTER TABLE public.remarketing_config ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "anon_all_remarketing_config" ON public.remarketing_config TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Templates de mensaje por categoria x temperatura
CREATE TABLE IF NOT EXISTS public.remarketing_templates (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at       TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  company_id       TEXT NOT NULL,
  nombre           TEXT NOT NULL,
  categoria_proc   TEXT NOT NULL CHECK (categoria_proc IN ('A', 'B', 'C', 'D')),
  temperatura      TEXT NOT NULL CHECK (temperatura IN ('frio', 'tibio', 'caliente', 'recall')),
  canal            TEXT NOT NULL DEFAULT 'whatsapp' CHECK (canal IN ('whatsapp', 'email', 'sms')),
  contenido        TEXT NOT NULL,
  variables        JSONB DEFAULT '[]',
  chatwoot_template_name  TEXT,
  activo           BOOLEAN DEFAULT true
);

ALTER TABLE public.remarketing_templates ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "anon_all_remarketing_templates" ON public.remarketing_templates TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_remarketing_templates_company
  ON remarketing_templates (company_id, categoria_proc, temperatura);

-- Historial de mensajes enviados (tracking anti-spam)
CREATE TABLE IF NOT EXISTS public.remarketing_contactos (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at       TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  company_id       TEXT NOT NULL,
  lead_id          BIGINT NOT NULL,
  lead_tabla       TEXT NOT NULL,
  lead_telefono    TEXT,
  lead_nombre      TEXT,
  template_id      BIGINT REFERENCES public.remarketing_templates(id),
  canal            TEXT DEFAULT 'whatsapp',
  mensaje          TEXT,
  enviado_at       TIMESTAMPTZ DEFAULT timezone('utc', now()),
  respondio        BOOLEAN DEFAULT false,
  respondio_at     TIMESTAMPTZ,
  campaign_id      BIGINT,
  estado           TEXT DEFAULT 'enviado' CHECK (estado IN ('enviado', 'entregado', 'leido', 'respondido', 'fallido'))
);

ALTER TABLE public.remarketing_contactos ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "anon_all_remarketing_contactos" ON public.remarketing_contactos TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_remarketing_contactos_lead
  ON remarketing_contactos (company_id, lead_id, lead_tabla);
CREATE INDEX IF NOT EXISTS idx_remarketing_contactos_enviado
  ON remarketing_contactos (company_id, enviado_at DESC);

-- Campanas masivas
CREATE TABLE IF NOT EXISTS public.remarketing_campaigns (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at       TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  company_id       TEXT NOT NULL,
  nombre           TEXT NOT NULL,
  tipo             TEXT DEFAULT 'seguimiento' CHECK (tipo IN ('seguimiento', 'reactivacion', 'recall', 'estacional', 'promocion')),
  segmento         JSONB NOT NULL DEFAULT '{}',
  template_id      BIGINT REFERENCES public.remarketing_templates(id),
  estado           TEXT DEFAULT 'borrador' CHECK (estado IN ('borrador', 'programada', 'enviando', 'completada', 'cancelada')),
  programada_para  TIMESTAMPTZ,
  total_leads      INT DEFAULT 0,
  enviados         INT DEFAULT 0,
  respondidos      INT DEFAULT 0,
  convertidos      INT DEFAULT 0,
  ejecutada_at     TIMESTAMPTZ,
  creado_por       TEXT
);

ALTER TABLE public.remarketing_campaigns ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "anon_all_remarketing_campaigns" ON public.remarketing_campaigns TO anon USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_remarketing_campaigns_company
  ON remarketing_campaigns (company_id, estado);

-- =====================================================================
-- Seed: Config de empresas con Chatwoot account IDs
-- =====================================================================
INSERT INTO public.remarketing_config (company_id, chatwoot_account_id, chatwoot_inbox_id) VALUES
  ('healup', 2, 1),
  ('solari', 2, 1),
  ('davila', 3, 1),
  ('clinicaarroyo', 5, 1),
  ('alegrated', 7, 1),
  ('brada', 8, 1),
  ('skip', 10, 1),
  ('origitec', 10, 1),
  ('estetikamedika', 14, 1),
  ('estasconsuerte', 2, 1),
  ('gatwick', 15, 1)
ON CONFLICT (company_id) DO NOTHING;

-- =====================================================================
-- Seed: Templates genericos (ejemplo Healup, replicar por empresa)
-- =====================================================================
INSERT INTO public.remarketing_templates (company_id, nombre, categoria_proc, temperatura, canal, contenido, variables) VALUES
-- Caliente Cat A
('healup', 'Caliente - Decision rapida - CTA', 'A', 'caliente', 'whatsapp',
 'Hola {{nombre}}, te separo tu cita de {{procedimiento}} para esta semana? Te paso disponibilidad.',
 '["nombre", "procedimiento"]'),
-- Caliente Cat B
('healup', 'Caliente - Ticket alto - Prueba social', 'B', 'caliente', 'whatsapp',
 'Hola {{nombre}}, te comparto un caso similar al tuyo de {{procedimiento}}. Te agendo una valoracion sin costo con la Dra.?',
 '["nombre", "procedimiento"]'),
-- Tibio Cat A
('healup', 'Tibio - Decision rapida - Objecion', 'A', 'tibio', 'whatsapp',
 'Hola {{nombre}}, {{procedimiento}} dura 45 minutos y la mayoria agenda en su hora de almuerzo. Te paso una hora que te calce?',
 '["nombre", "procedimiento"]'),
-- Tibio Cat B
('healup', 'Tibio - Ticket alto - Educacion', 'B', 'tibio', 'whatsapp',
 'Hola {{nombre}}, te comparto la guia rapida sobre {{procedimiento}}: como se planifica y que resultado esperar. Sin compromiso.',
 '["nombre", "procedimiento"]'),
-- Frio Cat A (campana)
('healup', 'Frio - Campana estacional', 'A', 'frio', 'whatsapp',
 '{{nombre}}, abrimos cupos de {{procedimiento}} este sabado. Promo del mes. Te separo?',
 '["nombre", "procedimiento"]'),
-- Frio Cat B (campana)
('healup', 'Frio - Evaluacion gratuita', 'B', 'frio', 'whatsapp',
 '{{nombre}}, en mayo abrimos consultas de evaluacion de {{procedimiento}} sin costo. Cupos limitados. Te separo una?',
 '["nombre", "procedimiento"]'),
-- Recall Cat A
('healup', 'Recall - Proxima sesion', 'A', 'recall', 'whatsapp',
 '{{nombre}}, la proxima sesion de {{procedimiento}} es ideal en 4 semanas. Te separo el turno?',
 '["nombre", "procedimiento"]'),
-- Recall Cat B
('healup', 'Recall - Retoque programado', 'B', 'recall', 'whatsapp',
 '{{nombre}}, ya pasaron varios meses de tu {{procedimiento}}. Es buen momento para una valoracion de retoque. Te separo con la Dra.?',
 '["nombre", "procedimiento"]')
ON CONFLICT DO NOTHING;
